formatter: "markdown" # this is required

version: "0.18.0"

recursive:
  enabled: false
  path: modules
  include-main: true

content: |-
  {{ .Header}}
  ## Diagram:
  ![Diagram](.docs/diagram.png)


  ## Example:

  ```hcl
  {{ include "examples/basic.tf"}}
  ```


  {{.Inputs}}
  {{.Outputs}}
  {{.Resources}}
  {{.Footer}}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
